apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: database
  name: database
  namespace: litres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: DB_NAME
            - name: DB_SERVER
            - name: HANGFIRE_PASSWORD
            - name: SA_PASSWORD
            - name: SA_USER
          image: net-literes-database
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd
                - -S
                - $(DB_SERVER)
                - -U
                - $(SA_USER)
                - -P
                - $(SA_PASSWORD)
                - -d
                - $(DB_NAME)
                - -C
                - -Q
                - SELECT 1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: litres-database
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/init-db.sh
              name: database-cm0
              subPath: init-db.sh
            - mountPath: /usr/src/app/create-databases.sql
              name: database-cm1
              subPath: create-databases.sql
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init-db.sh
                path: init-db.sh
            name: database-cm0
          name: database-cm0
        - configMap:
            items:
              - key: create-databases.sql
                path: create-databases.sql
            name: database-cm1
          name: database-cm1
