apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: database
