apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: frontend
          name: litres-frontend
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
