apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 8081
  selector:
    io.kompose.service: frontend
