apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migrate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: migrate
    spec:
      containers:
        - env:
            - name: DB_CONNECTION_STRING
            - name: DB_NAME
            - name: DB_SERVER
            - name: HANGFIRE_CONNECTION_STRING
            - name: HANGFIRE_PASSWORD
            - name: PAYMENT_SERVICE_URL
            - name: SA_PASSWORD
            - name: SA_USER
            - name: TEST_DB_CONNECTION_STRING
          image: migrate
          name: litres-migrate
      restartPolicy: Always
