apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Software\AAProgramming\ComplexProjects\Portfolio\.NET-Literes\kompose.exe convert -o .\komp_conv\
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "5271"
      port: 5271
      targetPort: 8080
  selector:
    io.kompose.service: server
