services:
  database:
    container_name: litres_database
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=_BEZ_Par0lya_007_
    volumes:
      - ./database/init-db.sh:/usr/src/app/init-db.sh
      - ./database/create-databases.sql:/usr/src/app/create-databases.sql

  payment:
    container_name: litres_payment
    build:
      context: ./backend/Litres.Payment
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database

  server:
    container_name: litres_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5271:8080"
    depends_on:
      - database
    entrypoint: ["./wait-for-db.sh", "database:1433", "--", "dotnet", "Litres.WebAPI.dll"]

  frontend:
    container_name: litres_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:8081"
    depends_on:
      - server
