resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/secret.yaml
  - config/scripts-configmap.yaml
  - database/database-deployment.yaml
  - database/database-service.yaml
  - storage/redis-deployment.yaml
  - storage/redis-service.yaml
  - storage/minio-deployment.yaml
  - storage/minio-service.yaml
  - jobs/migrate-job.yaml
  - services/payment-deployment.yaml
  - services/payment-service.yaml
  - services/server-deployment.yaml
  - services/server-service.yaml
  - services/frontend-deployment.yaml
  - services/frontend-service.yaml
  - networking/ingress.yaml
  