apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migrate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: migrate
    spec:
      containers:
        - env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_CONNECTION_STRING
            - name: HANGFIRE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HANGFIRE_CONNECTION_STRING
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_SERVICE_URL
            - name: TEST_DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TEST_DB_CONNECTION_STRING
            - name: ACCEPT_EULA
              value: "Y"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_SERVER
            - name: HANGFIRE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HANGFIRE_PASSWORD
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SA_PASSWORD
            - name: SA_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SA_USER
          image: coldezzt/net-litres-migrate
          name: litres-migrate
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
