apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: payment
  name: payment
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: payment
