apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: payment
    spec:
      containers:
        - image: coldezzt/net-litres-payment
          name: litres-payment
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
