apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:latest
          name: litres-redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
