apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\ruzan\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -o .\k8s\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: server
  name: server
spec:
  type: NodePort
  ports:
    - name: "5271"
      port: 5271
      targetPort: 8080
      nodePort: 31080
  selector:
    io.kompose.service: server
