// @generated by protobuf-ts 2.11.0
// @generated from protobuf file "chat.proto" (package "chat", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ChatService } from "./chat";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { Empty } from "./google/protobuf/empty";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ChatMessage } from "./chat";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chat.ChatService
 */
export interface IChatServiceClient {
    /**
     * @generated from protobuf rpc: Chat
     */
    chat(options?: RpcOptions): DuplexStreamingCall<ChatMessage, ChatMessage>;
    /**
     * @generated from protobuf rpc: Subscribe
     */
    subscribe(input: Empty, options?: RpcOptions): ServerStreamingCall<Empty, ChatMessage>;
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: ChatMessage, options?: RpcOptions): UnaryCall<ChatMessage, Empty>;
}
/**
 * @generated from protobuf service chat.ChatService
 */
export class ChatServiceClient implements IChatServiceClient, ServiceInfo {
    typeName = ChatService.typeName;
    methods = ChatService.methods;
    options = ChatService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Chat
     */
    chat(options?: RpcOptions): DuplexStreamingCall<ChatMessage, ChatMessage> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChatMessage, ChatMessage>("duplex", this._transport, method, opt);
    }
    /**
     * @generated from protobuf rpc: Subscribe
     */
    subscribe(input: Empty, options?: RpcOptions): ServerStreamingCall<Empty, ChatMessage> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, ChatMessage>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: ChatMessage, options?: RpcOptions): UnaryCall<ChatMessage, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChatMessage, Empty>("unary", this._transport, method, opt, input);
    }
}
