// <auto-generated />
using System;
using Litres.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Litres.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Favourites", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("Litres.Data.Models.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "J.K. Rowling is the author of the much-loved series of seven Harry Potter novels, originally published between 1997 and 2007. Along with the three companion books written for charity, the series has sold over 500 million copies, been translated into 80 languages, and made into eight blockbuster films.",
                            Name = "J. K. Rowling"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Donald John Trump (born June 14, 1946) is an American politician, media personality, and businessman who served as the 45th president of the United States from 2017 to 2021.",
                            Name = "Donald Trump"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Leo Tolstoy – Russian writer and thinker, participated in the defense of Sevastopol, was engaged in educational and journalistic activities. He was at the origins of Tolstoyism, a new religious movement.",
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Multi-Michelin starred chef and star of the small screen, Gordon Ramsay has opened a string of successful restaurants across the globe.",
                            Name = "Gordon Ramsey"
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("BookGenres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadable")
                        .HasColumnType("bit");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PublisherId")
                        .HasColumnType("bigint");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            BookGenres = "[2,3,6,12]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school and with the help of his friends, Ron Weasley and Hermione Granger, he faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-38-907435-4",
                            Name = "Harry Potter and the Philosopher Stone",
                            Price = 500,
                            PublicationDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 9L,
                            Rating = 4.7000000000000002,
                            SeriesId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 1L,
                            BookGenres = "[2,3,6,12]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling. The second novel in the Harry Potter series, Rowling continues the story of Harry Potter's second year at Hogwarts School of Witchcraft and Wizardry. Along with his friends Ron Weasley and Hermione Granger, Harry investigates a series of mysterious attacks that have targeted students at the school, leaving them petrified. The trio discover that the attacks are being carried out by the mysterious Chamber of Secrets and they must uncover the truth before it is too late.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-38-907436-1",
                            Name = "Harry Potter and the Chamber of Secrets",
                            Price = 550,
                            PublicationDate = new DateTime(1998, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 9L,
                            Rating = 4.5,
                            SeriesId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 1L,
                            BookGenres = "[2,3,6,12]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling. The third novel in the Harry Potter series, the book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with his friends Ron Weasley and Hermione Granger, Harry investigates the criminal Sirius Black, who is believed to be a supporter of the dark wizard Lord Voldemort. The trio uncover the truth about Sirius and a number of secrets from the past that have a profound impact on Harry's life.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-38-907437-8",
                            Name = "Harry Potter and the Prisoner of Azkaban",
                            Price = 600,
                            PublicationDate = new DateTime(1999, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 9L,
                            Rating = 4.7999999999999998,
                            SeriesId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 1L,
                            BookGenres = "[2,3,6,12]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "Harry Potter and the Goblet of Fire is a fantasy novel written by British author J. K. Rowling. The fourth novel in the Harry Potter series, the book follows Harry Potter, a young wizard, in his fourth year at Hogwarts School of Witchcraft and Wizardry. The story revolves around the Triwizard Tournament, where three magical schools compete against each other. However, during the tournament, Harry encounters the resurrected Lord Voldemort and his plans for revenge against Harry.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-38-907438-5",
                            Name = "Harry Potter and the Goblet of Fire",
                            Price = 650,
                            PublicationDate = new DateTime(2000, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 9L,
                            Rating = 4.7000000000000002,
                            SeriesId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = 1L,
                            BookGenres = "[2,3,6,12]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "Harry Potter and the Order of the Phoenix is a fantasy novel written by British author J. K. Rowling. The fifth novel in the Harry Potter series, the book follows Harry Potter, a young wizard, in his fifth year at Hogwarts School of Witchcraft and Wizardry. Harry and his friends form a secret defensive group called Dumbledore's Army to prepare for Lord Voldemort's return and the wizarding war that is about to erupt. As Harry faces challenges, he also experiences the emotional struggles of adolescence and deals with the oppressive authority at Hogwarts.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-38-907439-2",
                            Name = "Harry Potter and the Order of the Phoenix",
                            Price = 700,
                            PublicationDate = new DateTime(2003, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 9L,
                            Rating = 4.9000000000000004,
                            SeriesId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            AuthorId = 1L,
                            BookGenres = "[2,3,6,12]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J. K. Rowling. The sixth novel in the Harry Potter series, the book follows Harry Potter, a young wizard, in his sixth year at Hogwarts School of Witchcraft and Wizardry. As Harry prepares for the battle against Lord Voldemort, he uncovers important information about Voldemort's past and learns about the concept of Horcruxes. The story explores the darker side of magic and the sacrifices that need to be made in the face of ultimate evil.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-38-907440-8",
                            Name = "Harry Potter and the Half-Blood Prince",
                            Price = 750,
                            PublicationDate = new DateTime(2005, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 9L,
                            Rating = 4.7999999999999998,
                            SeriesId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            AuthorId = 1L,
                            BookGenres = "[2,3,6,12]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling. The seventh and final novel in the Harry Potter series, the book follows Harry Potter, a young wizard, in his seventh year at Hogwarts School of Witchcraft and Wizardry. As the wizarding war reaches its climax, Harry, Ron, and Hermione set out on a mission to destroy the remaining Horcruxes and defeat Lord Voldemort once and for all. The book explores themes of sacrifice, friendship, and the power of love in the face of evil.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-38-907441-5",
                            Name = "Harry Potter and the Deathly Hallows",
                            Price = 800,
                            PublicationDate = new DateTime(2007, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 9L,
                            Rating = 4.9000000000000004,
                            SeriesId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            AuthorId = 2L,
                            BookGenres = "[4]",
                            ContentUrl = "",
                            Count = 3000,
                            CoverUrl = "",
                            Description = "To become a truly rich person, you need to learn how to think like a billionaire. And here the real estate genius, bestselling author and TV star Donald Trump will come to your aid. He will show you how to properly treat money, career, your own talents and life in general. In this book, you will find excellent advice from a recognized expert on investing in real estate: from methods of communicating with brokers to recommendations on building renovation and real estate valuation methods.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-96-142785-1",
                            Name = "Think like a billionaire",
                            Price = 1000,
                            PublicationDate = new DateTime(2016, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 10L,
                            Rating = 3.8999999999999999
                        },
                        new
                        {
                            Id = 9L,
                            AuthorId = 3L,
                            BookGenres = "[6,15]",
                            ContentUrl = "",
                            Count = 5000,
                            CoverUrl = "",
                            Description = "The standard Russian text of War and Peace is divided into four books (comprising fifteen parts) and an epilogue in two parts. ... Although the book is mainly in Russian, significant portions of dialogue are in French. It has been suggested[14] that the use of French is a deliberate literary device, to portray artifice while Russian emerges as a language of sincerity, honesty, and seriousness.",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = true,
                            Isbn = "978-5-907577-08-4",
                            Name = "War and Peace",
                            Price = 400,
                            PublicationDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 10L,
                            AuthorId = 4L,
                            BookGenres = "[7]",
                            ContentUrl = "",
                            Count = 1000,
                            CoverUrl = "",
                            Description = "Do you want to cook a delicious homemade lunch, but don't know where to start? Are you confused in kitchen cabinets and afraid to pick up a mixer? Start your first steps in the challenging world of cooking with our beginner series!Here you will find the best recipes on the most important topics, a detailed description of the cooking stages, step-by-step photos and useful tips. The recipes are divided into three difficulty groups, from the easiest to those that will take a little work. This is a basic tutorial for an inexperienced cook. With it, you will learn how to stir, whip, stew, sift, smear, scroll and much more. Learn to cook with our books!",
                            IsApproved = false,
                            IsAvailable = false,
                            IsReadable = false,
                            Isbn = "978-5-04-155311-1",
                            Name = "Learning how to cook quick recipes for every day",
                            Price = 900,
                            PublicationDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Contract");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            SerialNumber = "AA-0001/01"
                        },
                        new
                        {
                            Id = 2L,
                            SerialNumber = "AA-0002/01"
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.ExternalService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ServiceToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ExternalService");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Google",
                            ServiceToken = "Google Litres 1234"
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PickupPointId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Harry Potter and the Philosopher's Stone * 1; Harry Potter and the Chamber of SecretsЫ * 1;",
                            PickupPointId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "The Lord of the Rings: The Fellowship of the Ring * 1; The Lord of the Rings: The Two Towers * 1;",
                            PickupPointId = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Pride and Prejudice by Jane Austen * 1; Sense and Sensibility by Jane Austen * 1;",
                            PickupPointId = 3L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Description = "To Kill a Mockingbird by Harper Lee * 1; The Great Gatsby by F. Scott Fitzgerald * 1;",
                            PickupPointId = 4L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "1984 by George Orwell * 1; Animal Farm by George Orwell * 1;",
                            PickupPointId = 5L,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            Description = "The Catcher in the Rye by J.D. Salinger * 1; Catch-22 by Joseph Heller * 1;",
                            PickupPointId = 6L,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Description = "The Chronicles of Narnia by C.S. Lewis * 1; The Hobbit by J.R.R. Tolkien * 1;",
                            PickupPointId = 7L,
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "The Da Vinci Code by Dan Brown * 1; Angels & Demons by Dan Brown * 1;",
                            PickupPointId = 8L,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            Description = "The Catcher in the Rye by J.D. Salinger * 1; Catch-22 by Joseph Heller * 1;",
                            PickupPointId = 9L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Description = "The Chronicles of Narnia by C.S. Lewis * 1; The Hobbit by J.R.R. Tolkien * 1;",
                            PickupPointId = 10L,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.PickupPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FiasAdress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("PickupPoint");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "ул. Саид-Галеева, д.27",
                            FiasAdress = "0ccc56fa-3cb7-4fc9-9627-8417383806bd",
                            WorkingHours = "10:00-22:00"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "ул. Сабан, д.7А",
                            FiasAdress = "9797a9b6-607d-40ed-83c6-2d473be17224",
                            WorkingHours = "09:00-21:00"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "ул. Ленинградская, д.32",
                            FiasAdress = "620d672a-17a7-4db2-821c-46dca70b5817",
                            WorkingHours = "09:00-23:00"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "ул. Проспет Победы, д.46",
                            FiasAdress = "cc72fb9d-4468-449a-a1fe-0d61effb2a5a",
                            WorkingHours = "10:00-22:00"
                        },
                        new
                        {
                            Id = 5L,
                            Address = "ул. Бондаренко, д.34",
                            FiasAdress = "a049a83e-8775-43df-adb4-d1c0f7d9b7a6",
                            WorkingHours = "10:00-22:00"
                        },
                        new
                        {
                            Id = 6L,
                            Address = "ул. Минская, д.46",
                            FiasAdress = "1166b9da-0d95-4179-a1d1-6fafb8250bc6",
                            WorkingHours = "09:00-23:00"
                        },
                        new
                        {
                            Id = 7L,
                            Address = "ул. Фатыха Амирхана, д.21",
                            FiasAdress = "f18d8663-31c9-42ba-819b-6274b1202980",
                            WorkingHours = "10:00-22:00"
                        },
                        new
                        {
                            Id = 8L,
                            Address = "ул. Щапова, д.2",
                            FiasAdress = "2a3a1e2f-f50b-4781-ab9a-450131086bc0",
                            WorkingHours = "00:00-23:59"
                        },
                        new
                        {
                            Id = 9L,
                            Address = "ул. Нурсултана Назарбаева, д.45А",
                            FiasAdress = "383e0f18-63b5-400d-8abb-cacd9f7f1854",
                            WorkingHours = "09:00-23:00"
                        },
                        new
                        {
                            Id = 10L,
                            Address = "ул. Петра Полушкина, д.6",
                            FiasAdress = "f717cf33-87d3-474a-93b3-0d4e804a5462",
                            WorkingHours = "08:00-21:00"
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<long>("PublisherId")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedBookId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("UpdatedBookId");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("Litres.Data.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ParentReviewId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ParentReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BookId = 1L,
                            Content = "This is the greatest book I've read. Made my childhood",
                            CreatedAt = new DateTime(2024, 3, 3, 19, 42, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Content = "Can't disagree more. Awful book",
                            CreatedAt = new DateTime(2024, 3, 3, 20, 13, 0, 0, DateTimeKind.Unspecified),
                            ParentReviewId = 1L,
                            Rating = 0,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            BookId = 2L,
                            Content = "A masterpiece! Couldn't put it down.",
                            CreatedAt = new DateTime(2024, 3, 4, 9, 27, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            BookId = 2L,
                            Content = "I found it quite boring. Couldn't get into the story.",
                            CreatedAt = new DateTime(2024, 3, 4, 10, 9, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            BookId = 3L,
                            Content = "Highly recommend! Amazing plot twists.",
                            CreatedAt = new DateTime(2024, 3, 4, 15, 56, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            BookId = 3L,
                            Content = "Waste of time. Predictable and unoriginal.",
                            CreatedAt = new DateTime(2024, 3, 4, 17, 21, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            BookId = 4L,
                            Content = "Not my cup of tea. Didn't connect with the characters.",
                            CreatedAt = new DateTime(2024, 3, 5, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            BookId = 4L,
                            Content = "Absolutely brilliant! A must-read for any fantasy lover.",
                            CreatedAt = new DateTime(2024, 3, 5, 12, 37, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            BookId = 5L,
                            Content = "Incredible book. Touching and thought-provoking.",
                            CreatedAt = new DateTime(2024, 3, 5, 19, 15, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            BookId = 5L,
                            Content = "Couldn't get into it. Slow-paced and uninteresting.",
                            CreatedAt = new DateTime(2024, 3, 5, 20, 59, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 10L
                        },
                        new
                        {
                            Id = 11L,
                            BookId = 6L,
                            Content = "Loved every page! Captivating and beautifully written.",
                            CreatedAt = new DateTime(2024, 3, 6, 11, 42, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            BookId = 6L,
                            Content = "Disappointing. Expected much more from the hype.",
                            CreatedAt = new DateTime(2024, 3, 6, 14, 17, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            BookId = 7L,
                            Content = "Couldn't put it down! Gripping and suspenseful.",
                            CreatedAt = new DateTime(2024, 3, 7, 9, 38, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 14L,
                            BookId = 7L,
                            Content = "Hated it. Didn't understand the point of the story.",
                            CreatedAt = new DateTime(2024, 3, 7, 13, 25, 0, 0, DateTimeKind.Unspecified),
                            Rating = 1,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 15L,
                            BookId = 8L,
                            Content = "Beautifully written. The author's words touched my soul.",
                            CreatedAt = new DateTime(2024, 3, 8, 16, 59, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 16L,
                            BookId = 8L,
                            Content = "Overrated. Too much hype for a mediocre story.",
                            CreatedAt = new DateTime(2024, 3, 8, 18, 42, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 17L,
                            BookId = 9L,
                            Content = "An absolute gem! Emotional and heartwarming.",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 17, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 7L
                        },
                        new
                        {
                            Id = 18L,
                            BookId = 9L,
                            Content = "Couldn't finish it. Lost interest halfway through.",
                            CreatedAt = new DateTime(2024, 3, 9, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            Rating = 2,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 21L,
                            Content = "Totally agree",
                            CreatedAt = new DateTime(2024, 3, 11, 20, 13, 0, 0, DateTimeKind.Unspecified),
                            ParentReviewId = 3L,
                            Rating = 0,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Content = "What a great review!",
                            CreatedAt = new DateTime(2024, 3, 11, 22, 17, 0, 0, DateTimeKind.Unspecified),
                            ParentReviewId = 3L,
                            Rating = 0,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 23L,
                            Content = "Thx :3",
                            CreatedAt = new DateTime(2024, 3, 12, 12, 37, 0, 0, DateTimeKind.Unspecified),
                            ParentReviewId = 22L,
                            Rating = 0,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.ReviewLike", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewLike");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsLike = true,
                            ReviewId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            IsLike = false,
                            ReviewId = 2L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            IsLike = true,
                            ReviewId = 3L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            IsLike = false,
                            ReviewId = 4L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            IsLike = true,
                            ReviewId = 5L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            IsLike = false,
                            ReviewId = 6L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            IsLike = true,
                            ReviewId = 7L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            IsLike = false,
                            ReviewId = 8L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 9L,
                            IsLike = true,
                            ReviewId = 9L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 10L,
                            IsLike = false,
                            ReviewId = 10L,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 11L,
                            IsLike = true,
                            ReviewId = 11L,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 12L,
                            IsLike = false,
                            ReviewId = 12L,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 13L,
                            IsLike = true,
                            ReviewId = 13L,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 14L,
                            IsLike = false,
                            ReviewId = 14L,
                            UserId = 7L
                        },
                        new
                        {
                            Id = 15L,
                            IsLike = true,
                            ReviewId = 15L,
                            UserId = 7L
                        },
                        new
                        {
                            Id = 16L,
                            IsLike = false,
                            ReviewId = 16L,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 17L,
                            IsLike = true,
                            ReviewId = 17L,
                            UserId = 8L
                        },
                        new
                        {
                            Id = 18L,
                            IsLike = false,
                            ReviewId = 18L,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 21L,
                            IsLike = true,
                            ReviewId = 21L,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 22L,
                            IsLike = false,
                            ReviewId = 22L,
                            UserId = 10L
                        },
                        new
                        {
                            Id = 23L,
                            IsLike = true,
                            ReviewId = 23L,
                            UserId = 10L
                        },
                        new
                        {
                            Id = 24L,
                            IsLike = false,
                            ReviewId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            IsLike = true,
                            ReviewId = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            IsLike = false,
                            ReviewId = 3L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 27L,
                            IsLike = true,
                            ReviewId = 4L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 28L,
                            IsLike = false,
                            ReviewId = 5L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 29L,
                            IsLike = true,
                            ReviewId = 6L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 30L,
                            IsLike = false,
                            ReviewId = 7L,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 31L,
                            IsLike = true,
                            ReviewId = 8L,
                            UserId = 5L
                        },
                        new
                        {
                            Id = 32L,
                            IsLike = false,
                            ReviewId = 9L,
                            UserId = 6L
                        },
                        new
                        {
                            Id = 33L,
                            IsLike = true,
                            ReviewId = 10L,
                            UserId = 6L
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.Series", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            Name = "The Adventures of Harry Potter"
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BooksAllowed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BooksAllowed = "[1]",
                            Name = "Free",
                            Price = 0
                        },
                        new
                        {
                            Id = 2L,
                            BooksAllowed = "[1,9,10,19]",
                            Name = "Students",
                            Price = 150
                        },
                        new
                        {
                            Id = 3L,
                            BooksAllowed = "[1,4,5,9,10,19]",
                            Name = "Scientific",
                            Price = 200
                        },
                        new
                        {
                            Id = 4L,
                            BooksAllowed = "[]",
                            Name = "Premium",
                            Price = 0
                        },
                        new
                        {
                            Id = 5L,
                            BooksAllowed = "[1,6,8,11]",
                            Name = "Custom",
                            Price = 0
                        },
                        new
                        {
                            Id = 6L,
                            BooksAllowed = "[7,16,17,18]",
                            Name = "Custom",
                            Price = 0
                        });
                });

            modelBuilder.Entity("Litres.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("/");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscriptionActiveUntil")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Wallet")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "40cec47f-57a4-462a-893b-d1a63f6fcd6d",
                            Email = "a@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "User A",
                            PasswordHash = "aaa",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1L,
                            TwoFactorEnabled = false,
                            Wallet = 0.00m
                        },
                        new
                        {
                            Id = 2L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "6f4e7aea-53c7-4641-ba5f-8c8f19722066",
                            Email = "b@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "User B",
                            PasswordHash = "bbb",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 2L,
                            TwoFactorEnabled = false,
                            Wallet = 3.59m
                        },
                        new
                        {
                            Id = 3L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "995f15d6-6156-44f3-b3a1-fb3c8d3d570b",
                            Email = "c@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "User C",
                            PasswordHash = "ccc",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 3L,
                            TwoFactorEnabled = false,
                            Wallet = 10.00m
                        },
                        new
                        {
                            Id = 4L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "9885f582-8c0e-4076-9581-d64502420e73",
                            Email = "d@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "User D",
                            PasswordHash = "ddd",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 4L,
                            TwoFactorEnabled = false,
                            Wallet = 5.32m
                        },
                        new
                        {
                            Id = 5L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "50564fd9-8933-4757-881f-839d41db2efd",
                            Email = "e@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "User E",
                            PasswordHash = "eee",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 5L,
                            TwoFactorEnabled = false,
                            Wallet = 1.99m
                        },
                        new
                        {
                            Id = 6L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "35eddc2e-c9ca-4640-ad1f-9175a2cb93d9",
                            Email = "f@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "User F",
                            PasswordHash = "fff",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 6L,
                            TwoFactorEnabled = false,
                            Wallet = 7.25m
                        },
                        new
                        {
                            Id = 7L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "f47e3699-9c6f-463e-b8b2-c3cecbbc69ea",
                            Email = "g@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "User G",
                            PasswordHash = "ggg",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1L,
                            TwoFactorEnabled = false,
                            Wallet = 0.50m
                        },
                        new
                        {
                            Id = 8L,
                            AccessFailedCount = 0,
                            AvatarUrl = "",
                            ConcurrencyStamp = "79302e5d-c9b0-4dee-9b7a-5e486f638a23",
                            Email = "h@mail.com",
                            EmailConfirmed = false,
                            IsModerator = true,
                            LockoutEnabled = false,
                            Name = "User H",
                            PasswordHash = "hhh",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            Wallet = 0m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Purchased", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("Purchased");
                });

            modelBuilder.Entity("UserExternalServices", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExternalServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "ExternalServiceId");

                    b.HasIndex("ExternalServiceId");

                    b.ToTable("UserExternalServices");
                });

            modelBuilder.Entity("Litres.Data.Models.Publisher", b =>
                {
                    b.HasBaseType("Litres.Data.Models.User");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.HasIndex("ContractId");

                    b.ToTable("Publisher", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 9L,
                            AccessFailedCount = 0,
                            AvatarUrl = "aa",
                            ConcurrencyStamp = "1ca0e690-1fd2-42bb-bfa6-a3d86807ff18",
                            Email = "pA@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "Publisher A",
                            PasswordHash = "aaa",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            Wallet = 6.78m,
                            ContractId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            AccessFailedCount = 0,
                            AvatarUrl = "bb",
                            ConcurrencyStamp = "ea884586-2655-495b-9d04-48d0744e52c4",
                            Email = "pB@mail.com",
                            EmailConfirmed = false,
                            IsModerator = false,
                            LockoutEnabled = false,
                            Name = "Publisher B",
                            PasswordHash = "bbb",
                            PhoneNumberConfirmed = false,
                            SubscriptionActiveUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            Wallet = 4.50m,
                            ContractId = 2L
                        });
                });

            modelBuilder.Entity("Favourites", b =>
                {
                    b.HasOne("Litres.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Litres.Data.Models.Book", b =>
                {
                    b.HasOne("Litres.Data.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Litres.Data.Models.Series", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Publisher");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Litres.Data.Models.Order", b =>
                {
                    b.HasOne("Litres.Data.Models.PickupPoint", "PickupPoint")
                        .WithMany("Orders")
                        .HasForeignKey("PickupPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Litres.Data.Models.Request", b =>
                {
                    b.HasOne("Litres.Data.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.Publisher", "Publisher")
                        .WithMany("Requests")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.Book", "UpdatedBook")
                        .WithMany()
                        .HasForeignKey("UpdatedBookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Publisher");

                    b.Navigation("UpdatedBook");
                });

            modelBuilder.Entity("Litres.Data.Models.Review", b =>
                {
                    b.HasOne("Litres.Data.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Litres.Data.Models.Review", "ParentReview")
                        .WithMany()
                        .HasForeignKey("ParentReviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Litres.Data.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("ParentReview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Litres.Data.Models.ReviewLike", b =>
                {
                    b.HasOne("Litres.Data.Models.Review", "Review")
                        .WithMany("ReviewLikes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.User", "User")
                        .WithMany("ReviewLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Litres.Data.Models.Series", b =>
                {
                    b.HasOne("Litres.Data.Models.Author", "Author")
                        .WithMany("Series")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Litres.Data.Models.User", b =>
                {
                    b.HasOne("Litres.Data.Models.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Purchased", b =>
                {
                    b.HasOne("Litres.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UserExternalServices", b =>
                {
                    b.HasOne("Litres.Data.Models.ExternalService", null)
                        .WithMany()
                        .HasForeignKey("ExternalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Litres.Data.Models.Publisher", b =>
                {
                    b.HasOne("Litres.Data.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Litres.Data.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Litres.Data.Models.Publisher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Litres.Data.Models.Author", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Litres.Data.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Litres.Data.Models.PickupPoint", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Litres.Data.Models.Review", b =>
                {
                    b.Navigation("ReviewLikes");
                });

            modelBuilder.Entity("Litres.Data.Models.Series", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Litres.Data.Models.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Litres.Data.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ReviewLikes");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Litres.Data.Models.Publisher", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
