apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: litres
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: wait-for-server
        image: busybox
        command: ['sh', '-c', 'until nslookup server; do echo waiting for server; sleep 2; done']
      containers:
      - name: frontend
        image: node:20-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
