apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: litres
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      initContainers:
      - name: wait-for-migrate
        image: busybox
        command: ['sh', '-c', 'until nslookup migrate; do echo "waiting for migrate"; sleep 2; done']
      containers:
      - name: server
        image: mcr.microsoft.com/dotnet/aspnet:8.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_SERVER
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SA_PASSWORD
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/wait-for-db.sh
          name: db-scripts
          subPath: wait-for-db.sh
      volumes:
      - name: db-scripts
        configMap:
          name: db-scripts
          defaultMode: 0777
