name: check


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build in Debug mode
        run: dotnet build --no-restore
      - name: Tests
        run: dotnet test
        working-directory: Tests
      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: | 
         curl -Os https://uploader.codecov.io/latest/linux/codecov
         find . -iregex "codecov.*"
         chmod +x codecov 
         ./codecov -t ${CODECOV_TOKEN}

