name: "dotnet-build"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build in Debug mode
        run: dotnet build --no-restore
      - name: Unit tests
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings ../.github/coverlet.runsettings
        working-directory: Tests.Unit
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build in Debug mode
        run: dotnet build
      - name: Unit tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build
        working-directory: Tests.Unit
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: "Tests.Unit/TestResults/*.trx"
