name: 'Test Report'
on:
  workflow_run:
    workflows: ['check']                     # runs after CI workflow
    types:
      - completed
jobs:
  check:
    runs-on: ubunty-latest
    steps:
    - name: Check GitHub token
      run: echo $GITHUB
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: test-report                  # Name of the check run which will be created
          path: 'Tests/TestResults/*.trx'                     # Path to test results (inside artifact .zip)
          reporter: dotnet-trx   # Format of test results
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB}}
    permissions: write-all
