name: "Test Report"
on:
  workflow_run:
    workflows: ["dotner-build"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Test Reporter
        uses: dorny/test-reporter@v1.8.0
        with:
          artifact: test-results
          name: report
          path: "Tests.Unit/TestResults/*.trx"
          reporter: dotnet-trx
    permissions: write-all
